### Verbo GET - listar todos
GET http://127.0.0.1:8000/cliente/

### Verbo GET - listar um              RAFAEL WALTRICK
GET http://127.0.0.1:8000/cliente/10

### Verbo POST - adicionar
POST http://127.0.0.1:8000/cliente/
content-type: application/json

{
    "nome": "Rafael wal",
    "cpf": "21",
    "telefone": "43"
}

### Verbo PUT - atualiza
PUT http://127.0.0.1:8000/cliente/2
content-type: application/json

{
    "nome": "Rafael teste",
    "cpf": "1",
    "telefone": "4"
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/cliente/3