### Verbo GET - listar todos
GET http://127.0.0.1:8000/funcionario/

### Verbo GET - listar um
GET http://127.0.0.1:8000/funcionario/10

### Verbo POST - adicionar
POST http://127.0.0.1:8000/funcionario/
content-type: application/json

{
    "nome": "Rafael tes",
    "matricula": "r",
    "cpf": "133",
    "telefone": "tel2383738",
    "grupo": 1,
    "senha": "ee"
}

### Verbo PUT - atualiza
PUT http://127.0.0.1:8000/funcionario/2
content-type: application/json

{
    "nome": "Rafael Waltrick",
    "matricula": "ra12353",
    "cpf": "12",
    "telefone": "tel2383738",
    "grupo": 1,
    "senha": "dc7378a6b6316017b81c51d720e7"
}

### Verbo DELETE - excluir     
DELETE http://127.0.0.1:8000/funcionario/3

## RAFAEL WALTRICK