### Verbo GET - listar todos
GET http://127.0.0.1:8000/produto/

### Verbo GET - listar um                      RAFAEL WALTRICKs
GET http://127.0.0.1:8000/produto/10

### Verbo POST - adicionar
POST http://127.0.0.1:8000/produto/
content-type: application/json

{
    "nome": "Produto Teste",
    "descricao": "Produto criado para teste",
    "valor": 10.50
}

### Verbo PUT - atualiza
PUT http://127.0.0.1:8000/produto/2
content-type: application/json

{
    "nome": "Produto Atualizado",
    "descricao": "Produto alterado",
    "valor": 15.90
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/produto/3