### Verbo GET - listar todos
GET http://127.0.0.1:8000/cliente/

### Verbo GET - listar um              RAFAEL WALTRICK
GET http://127.0.0.1:8000/cliente/10

### Verbo POST - adicionar
POST http://127.0.0.1:8000/cliente/
content-type: application/json

{
    "nome": "Rafael Waltrick",
    "cpf": "12345678900",
    "telefone": "49999999999"
}

### Verbo PUT - atualiza
PUT http://127.0.0.1:8000/cliente/2
content-type: application/json

{
    "nome": "Rafael Waltrick",
    "cpf": "12345678900",
    "telefone": "48888888888"
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/cliente/3